giturdone/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


# Include namespace in the url's

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^quiz/', include('giturdone_quiz.urls', namespace="giturdone_quiz")),
    url(r'^quiz/$', 'giturdone_quiz.views.quiz', name='index'),
    url(r'^quiz_selection/', 'giturdone_quiz.views.quiz_selection', name='quiz_selection'),
    url(r'^short_answer_quiz_categories/', 'giturdone_quiz.views.short_answer_quiz_categories', name='short_answer_quiz_categories'),
    url(r'^$', 'giturdone_quiz.views.index', name='index'),
    url(r'^results/', 'giturdone_quiz.views.results', name='results'),
    url(r'^tools/', 'giturdone_quiz.views.tools', name='tools'),
    url(r'^feynman_technique_quiz/', 'giturdone_quiz.views.feynman_technique_quiz', name='feynman_technique_quiz'),
    url(r'^feynman_technique_quiz/(?P<question_id>[0-9]+)/results/$', 'giturdone_quiz.views.ftq_results', name='ftq_results'),
    url(r'^multiple_choice_quiz/', 'giturdone_quiz.views.multiple_choice_quiz', name='multiple_choice_quiz'),
    url(r'^short_answer_quiz_graphs/', 'giturdone_quiz.views.short_answer_quiz_graphs', name='short_answer_quiz_graphs'),
# Left line below in prod version for now just in case it is needed
#    url(r'^quiz/', 'giturdone_quiz.views.git_quiz', name='git_quiz'),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

giturdone_quiz/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # ex: /quiz/
    url(r'^quiz_selection/', views.quiz_selection, name='quiz_selection'),
#   url(r'^$', views.git_quiz, name='index'),
    url(r'^quiz/$', views.quiz, name='index'),
    url(r'^resources/', views.git_resources, name='resources'),
    # ex: /quiz/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /quiz/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^reset_scores/', views.reset_scores, name='reset_scores'),
    url(r'^short_answer_quiz_categories/', 'giturdone_quiz.views.short_answer_quiz_categories', name='short_answer_quiz_categories'),
    url(r'^feynman_technique_quiz/$', views.feynman_technique_quiz, name='feynman_technique_quiz'),
    url(r'^feynman_technique_quiz/(?P<question_id>[0-9]+)/$', 'giturdone_quiz.views.ftq_detail', name='ftq_detail'),
    url(r'^feynman_technique_quiz/(?P<question_id>[0-9]+)/results/$', 'giturdone_quiz.views.ftq_results', name='ftq_results'),
    url(r'^feynman_technique_quiz/reset_scores/$', views.ftq_reset_scores, name='ftq_reset_scores'),
    url(r'^multiple_choice_quiz/$', views.multiple_choice_quiz, name='multiple_choice_quiz'),
    url(r'^multiple_choice_quiz/(?P<question_id>[0-9]+)/$', 'giturdone_quiz.views.multiple_choice_quiz_detail', name='multiple_choice_quiz_detail'),
    url(r'^multiple_choice_quiz/(?P<question_id>[0-9]+)/vote/$', 'giturdone_quiz.views.vote', name='vote'),
    url(r'^multiple_choice_quiz/(?P<question_id>[0-9]+)/results/$', 'giturdone_quiz.views.multiple_choice_quiz_results', name='multiple_choice_quiz_results'),
    url(r'^short_answer_quiz_graphs/', 'giturdone_quiz.views.short_answer_quiz_graphs', name='short_answer_quiz_graphs'),


#    url(r'^(?P<question_id>[0-9]+)/vote/$', 'giturdone_quiz.views.vote', name='vote'),
#    url(r'^(?P<question_id>[0-9]+)/vote/results/$', 'giturdone_quiz.views.multiple_choice_quiz_results', name='multiple_choice_quiz_results'),
    # ex: /quiz/5/vote/
# Note: the answers url is not being used in the app but is left here
# as an example for future versions
#    url(r'^(?P<question_id>[0-9]+)/answer/$', views.answer, name='answer'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

giturdone_quiz/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

# The following Question & Answer models are for the Short Answer Quiz

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    category = models.CharField(max_length=30)

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    answers = models.IntegerField(default=0)
    correct_answer = models.CharField(max_length=200, default='Linus Torvalds')
    total_correct_answers = models.IntegerField(default=0)
    total_wrong_answers = models.IntegerField(default=0)
    image = models.ImageField(upload_to='post_image', blank=True)

    def __unicode__(self):
        return self.answer_text


# The following Ftq_Question & Ftq_Answer models are for the
# Feynman Technique Quiz

class Ftq_Question(models.Model):
    question_text = models.CharField(max_length=400)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Ftq_Answer(models.Model):
    question = models.ForeignKey(Ftq_Question)
    answer_text = models.CharField(max_length=1200)
    image = models.ImageField(upload_to='post_image', blank=True)
    knowledge_mastery = models.IntegerField(default=0)
    knowledge_needs_improvement = models.IntegerField(default=0)
    knowledge_black_hole = models.IntegerField(default=0)


    def __unicode__(self):
        return self.answer_text



# The following Mc_Question & Mc_Answer models are for the
# Feynman Technique Quiz

class Mc_Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Mc_Answer(models.Model):
    question = models.ForeignKey(Mc_Question)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    correct_answer = models.CharField(max_length=200, default='Linus Torvalds')
    image = models.ImageField(upload_to='post_image', blank=True)

    def __unicode__(self):
        return self.answer_text

giturdone_quiz/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from . models import Answer, Question
import random
import datetime
from django.utils.encoding import *
# The line below imports the user_response variable from the user_response.py file
from . user_response import user_response
from processors import custom_processor
from django.db.models import Sum
from . models import Ftq_Question, Ftq_Answer
from . models import Mc_Question, Mc_Answer
import re

# TODO add comments to this module
# TODO add a button that allows computer user to zero out their scores
# TODO add functionality that zeros out scores on logout


# Create your views here.



# Note the index page used in the index function below tells the computer
# user about the application and what it is meant to be used for

# The following function renders the About Page

def index(request):
    return render(request, 'index.html')

# The following functions are for the Short Answer Quiz
# quiz_selection page takes a user_response as input and writes the response to giturdone_quiz/user_response.py

def quiz_selection(request):
    if request.method == 'POST':
        user_response = request.POST.get('textfield', None)
        user_response = smart_text(user_response)
        f = open('giturdone_quiz/user_response.py', 'w')
        # the line below write the text 'user_response = ' and concats the user_response the str function gets rid of u in front of string
        f.write('user_response = ' + repr(str(user_response)))
        f.close()
    return render(request, 'giturdone_quiz/quiz_selection.html')

# The function below will take the short answer quiz category user response and display
# the questions for the selected category

def quiz(request):
    if request.method == 'POST':
        user_response = request.POST.get('textfield', None)
        user_response = smart_text(user_response)
        f = open('giturdone_quiz/user_response.py', 'w')
        # the line below writes the text 'user_response = ' and concats the user_response the str function gets rid of u in front of string
        f.write('user_response = ' + repr(str(user_response)))
        f.close()
    else:
        f = open('giturdone_quiz/user_response.py', 'rb')
        user_response = f.read()
        f.close()
        # regular expression below reads the text between single quotes
        user_response=re.findall(r"'(.*?)'", user_response, re.DOTALL)
        # reads the first element in the user_response list
        user_response=user_response[0]
        user_response = smart_text(user_response)
    if user_response == '':
        return render(request, 'giturdone_quiz/index.html')
    if user_response == '1':
        latest_question_list = Question.objects.filter(category="Git Basics")
    if user_response == '2':
        latest_question_list = Question.objects.filter(category="Git Undoing Changes")
    if user_response == '3':
        latest_question_list = Question.objects.filter(category="Git Rewriting History")
    if user_response == '4':
        latest_question_list = Question.objects.filter(category="Git Branches")
    if user_response == '5':
        latest_question_list = Question.objects.filter(category="Git Remote Repositories")
    if user_response == '6':
        latest_question_list = Question.objects.filter(category="Git Config")
    if user_response == '7':
        latest_question_list = Question.objects.filter(category="Git Log")
    if user_response == '8':
        latest_question_list = Question.objects.filter(category="Git Diff")
    if user_response == '9':
        latest_question_list = Question.objects.filter(category="Git Reset")
    if user_response == '10':
        latest_question_list = Question.objects.filter(category="Git Rebase")
    if user_response == '11':
        latest_question_list = Question.objects.filter(category="Git Pull")
    if user_response == '12':
        latest_question_list = Question.objects.filter(category="Git Push")
    context = {'user_response': user_response, 'latest_question_list': latest_question_list}
    return render(request, 'giturdone_quiz/index.html', context)


def git_resources(request):
        return render(request, 'giturdone_quiz/resources.html')

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'giturdone_quiz/detail.html', {'question': question})


def results(request, question_id):
    latest_question_list = Question.objects.order_by('?')
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=question_id)
        selected_answer = Answer.objects.get(question_id=question.id)
        # Gets my_answer -> the answer associated with question_id
        my_answer = Answer.objects.filter(question_id=question_id)
        # Get the image "post_image/filename" for my_answer
        for item in my_answer:
            image = item.image
        image=str(item.image)

        # Concatenates "/media/" + "post_image/filename"
        image=("/media/" + (image))
        user_answer = request.POST.get('textfield', None)
        # Get the question object
        q = Question.objects.get(pk=question_id)
        # Get all the answers associated with the question object
        a = q.answer_set.all()
        # Get the first element in the list of answers
        value = a[0]
        # smart_text is a django utility that converts an object to a unicode string
        correct_answer = smart_text(value)
        # code for score calculator
        # initialize variables
        sum = 0
        total_correct_answers=0
        ttl_correct = 0
        ttl_c = 0
        total_wrong_answers = 0
        ttl_wrong = 0
        ttl_w = 0
        ttl_questions_answered = 0
        score = 0
        Grade = str("")
        # if correct answer increment total_correct_answers by 1 for the selected answer
        if correct_answer == user_answer:
            selected_answer.total_correct_answers += 1
            selected_answer.save()
        else:
        # if wrong answer increment total_wrong_answers by for the selected answer
            selected_answer.total_wrong_answers += 1
            selected_answer.save()
        # add up all the total_correct_answers -> produces a dictionary
        ttl_correct = Answer.objects.aggregate(Sum('total_correct_answers'))
        # assign the dictionary value to ttl_c
        ttl_c = (ttl_correct["total_correct_answers__sum"])
        # add up all the total_wrong_answers -> produces a dictionary
        ttl_wrong = Answer.objects.aggregate(Sum('total_wrong_answers'))
        # assign the dictionary value to ttl_w
        ttl_w = (ttl_wrong["total_wrong_answers__sum"])
        # calculate total questions answered
        ttl_questions_answered = ttl_c + ttl_w
        # calculate quiz score
        score = (float(ttl_c)/float(ttl_questions_answered) * 100)
        # make score and integer so that if elif statements below handle the score value correctly
        score = round(int(score), 2)
        if score in range(90,101):
            Grade = "A"
        elif score in range(80,90):
            Grade = "B"
        elif score in range(70,80):
            Grade = "C"
        elif score in range(60,70):
            Grade = "D"
        elif score in range(0,59):
            Grade = "F"
        context = {'latest_question_list': latest_question_list, 'answer': user_answer,
        'question': question, 'correct_answer': correct_answer, 'Grade':Grade,
        'score':score, 'total_questions_answered': ttl_questions_answered,
        'total_correct_answers': ttl_c, 'total_wrong_answers': ttl_w, 'image': image}
    return render(request, 'giturdone_quiz/results.html', context)


def reset_scores(request):
    answer_item = 0
    answers = Answer.objects.all()
    for answer_item in answers:
        answer_item.total_correct_answers = 0
        answer_item.total_wrong_answers = 0
        answer_item.save()
    return render(request, 'giturdone_quiz/reset_scores.html')

def short_answer_quiz_categories(request):
    if request.method == 'POST':
        return render(request, 'giturdone_quiz/index.html')
    else:
        return render(request, 'giturdone_quiz/short_answer_quiz_categories.html')


def short_answer_quiz_graphs(request):
    # do the work
    # Sort answers by total_wrong_answers_field
    wrong_answers_ordered = Answer.objects.order_by('total_wrong_answers')
    # Set counter to 0
    count = 0
    # Count total answers
    for answer in wrong_answers_ordered:
        count = count + 1
    total = count
    # assign last and first elements in range
    last_element_in_range = total
    first_element_in_range = last_element_in_range - 6
    wrong_answers_ordered = Answer.objects.order_by('total_wrong_answers')
    wrong_answers_ordered = wrong_answers_ordered.values()
    wrong_answers_ordered = wrong_answers_ordered.order_by("total_wrong_answers")
    index = first_element_in_range
    # create empty context dictionary
    context = {}
    for values in range(first_element_in_range, last_element_in_range):
        wrong_answers_ordered = Answer.objects.order_by('total_wrong_answers')
        wrong_answers_ordered = wrong_answers_ordered.values()
        my_dict = wrong_answers_ordered[index]
        id = my_dict["question_id"]
        q = Question.objects.get(id=id)
        if index == first_element_in_range:
            question1 = Question.objects.get(pk=id)
            question1_total_wrong_answers = my_dict["total_wrong_answers"]
            context["question1"] = question1
            context["question1_total_wrong_answers"] = question1_total_wrong_answers
        elif index == first_element_in_range + 1:

giturdone_quiz/templates/giturdone_quiz/detail.html
{% extends 'giturdone_quiz/base.html' %}

{% block title %}Git Ur Done Detail{% endblock %}



{% block body %}
<div class="w3-container w3-yellow">

    <h1 style="text-align:center; color:blue;">Short Answer Quiz</h1>
    <br>
    <br>

    <h2 style="color:blue">{{ question.question_text }}</h2>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'giturdone_quiz:results' question.id %}" method="post">
    {% csrf_token %}
      <table>{{ form.as_table }}</table>
       <p><label for="id_name"> Type Your Answer:</label>
        <input align="left" class="textinput textInput form-control size=50" id="id_name" maxlength="50" name="textfield" type="text" style="width:400px"/>
      <input type="submit" value="Submit" />
    </form>
<p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
</div>
{% endblock %}

giturdone_quiz/templates/giturdone_quiz/feynman_technique_quiz.html
{% extends 'giturdone_quiz/base.html' %}

{% block title %}FTQ Quiz{% endblock %}



{% block body %}

<div class="w3-container w3-yellow">

    <p font-size="20px" style="text-align:justify;">

    <center><img src="/static/images/richard_feynman.png" style="width250px:height250px" align="center"></center>


    <br>
    Richard Feynman was born on May 11, 1918 and lived until February 15, 1988.  He was a
    brilliant American theoretical physicist.  He was also an excellent teacher and had the
    ability to explain even the most complex ideas and concepts in simple easy to understand
    language.  The Feynman technique which is explained below is named after
    <a href="https://en.wikipedia.org/wiki/Richard_Feynman" target="_blank button type="button"  class="btn btn-lg btn-primary" disabled>Richard Feynman</button></a>
    The Feynman Technique is one of the best ways to quickly learn new information.
    <br>
    <br>
    Step 1
    <br>
    Write the name of the concept at the top of a blank piece of paper.<br>
    <br>
    Step 2<br>

    Write down an explanation of the concept on the page. Use plain English. Pretend you are teaching it to someone else (e.g a new student). This should highlight what you understand, but more importantly pinpoint what you don't quite know.<br>
    <br>
    Step 3<br>

    Review what you have pinpointed you don't know. Go back to the source material, re-read, and re-learn it.<br>Repeat Step 2.<br>
    <br>
    Step 4
    <br>
    If you are using overly wordy or confusing language (or simply paraphrasing the source material) try again so you filter the content. Simplify your language, and where possible use simple analogy.
    Conclusion

    That's it. A simple and powerful technique to ensure you can rapidly learn and retain new concepts and information.
    <br>
    <br>

    <h3 style="color:blue">Click on Question Below</h3>
    <br>


    <h3 style="color:blue">
    {% if ftq_questions %}
        <ul>
        {% for question in ftq_questions %}
            <li><a href="{% url 'giturdone_quiz:ftq_detail' question.id %}">{{ question }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No questions are available.</p>
    {% endif %}
    </h3>



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
</div>
{% endblock %}

giturdone_quiz/templates/giturdone_quiz/ftq_reset_scores.html
{% extends 'giturdone_quiz/base.html' %}

{% block title %}FTQ Reset Scores{% endblock %}



{% block body %}

<div class="w3-container w3-yellow">



    <center>
    <h2 style="color:blue">Your Scores Have Been Zeroed!</h2>
    </center>

<p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
</div>
{% endblock %}

giturdone_quiz/templates/giturdone_quiz/index.html
{% extends 'giturdone_quiz/base.html' %}

{% block title %}Git Ur Done Detail{% endblock %}



{% block body %}
<div class="w3-container w3-yellow">
    <h1 style="text-align:center; color:blue;">Short Answer Quiz</h1>
    <br>
    <br>
    <h3 style="color:blue;">Click On A Question Below

    <br>
    <br>
    <br>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'giturdone_quiz:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No questions are available.</p>
    {% endif %}
    </h3>

<p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
</div>
{% endblock %}

giturdone_quiz/templates/giturdone_quiz/multiple_choice_quiz_detail.html
{% extends 'giturdone_quiz/base.html' %}

{% block title %}Multiple Choice Quiz Detail{% endblock %}



{% block body %}
<div class="w3-container w3-yellow">

    <h1 style="text-align:center; color:blue;">Multiple Choice Quiz Detail</h1>
    <br>
    <br>
    <br>
    <br>
    <h3>{{selected_answer}}</h3>
    <br>
    <br>
    <br>

     <h2 style="color:blue;">{{ question.question_text }}</h2>



    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'giturdone_quiz:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for answer in question.mc_answer_set.all %}
        <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
        <label for="answer{{ forloop.counter }}">{{ answer.answer_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Submit" />
    </form>

<p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
</div>
{% endblock %}

giturdone_quiz/templates/giturdone_quiz/multiple_choice_quiz_results.html
{% extends 'giturdone_quiz/base.html' %}

{% block title %}Git Ur Done Resources{% endblock %}



{% block body %}
<div class="w3-container w3-yellow">

    <!--
        <h3 align="left" style="color:Blue;">Grade: {{ Grade }}</h3>
        <h3 align="left" style="color:Blue;">Score: {{ score }} %</h3>
        <h3 align="left" style="color:Blue;">Total Questions Answered: {{ total_questions_answered }}</h3>
        <h3 align="left" style="color:Blue;">Correct Answers: {{ total_correct_answers }}</h3>
        <h3 align="left" style="color:Blue;">Wrong Answers: {{ total_wrong_answers }}</h3>
    -->

    <form action="{% url 'giturdone_quiz:ftq_reset_scores' %}" method="post">
    {% csrf_token %}
      <table>{{ form.as_table }}</table>
       <p><label for="id_name"> Click Button To Reset Your Scores To Zero:</label>
    <!--<input align="left" class="textinput textInput form-control size=50" id="id_name" maxlength="50" name="textfield" type="text" style="width:400px"/></p>
      <input type="submit" style=color:red value="Reset Scores To Zero" /></p>-->
    <br>
      <button type="submit" class="btn btn-danger btn-sm id="id_name">Reset Multiple Choice Quiz Scores To Zero</button>
    </form>

    <br>
        <a href="http://localhost:8000/multiple_choice_quiz/" target="_blank" button type="button" class="btn btn-lg btn-primary" disabled>Return To Multiple Choice Quiz</button></a>

    <center>
          {% if correct_answer == user_selected_answer %}
            <img src="/static/images/two_thumbs_up.png" style="width:125px;height:100px;">
            <h3 style="color:blue">Yep!...the correct answer is</h3><h3 style="color:green">{{ user_selected_answer }} </h3>
          {% else %}
            <img src="/static/images/thumbs_down.png" style="width:125px;height:100px;">
            <h3 style="color:blue">Nope!....the correct answer is</h3><h3 style="color:green"> {{ correct_answer }}</h3><br>
            <h3 style="color:blue"> Your answer was</h3><h3 style="color:red"> {{ user_selected_answer }} </h3>
          {% endif %}

    <!-- if the 7th element is a string then "post" included in /image/post/*.png -->
    {% if image.7 == "p" and correct_answer == user_selected_answer %}
                <img src= "{{ image }}" style="width:250px;height:250px;">
    {% endif %}




    {% for answer in question.mc_answer_set.all %}
        {% if answer.votes = value %}
            <h3>You chose {{ answer.answer_text }}</h3>
        {% endif %}
        <li>{{ answer.answer_text }} -- {{ answer.votes }} vote{{ answer.votes|pluralize }}</li>
    {% endfor %}
    </ul>


    </center>



<p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
</div>
{% endblock %}

giturdone_quiz/templates/giturdone_quiz/reset_scores.html
{% extends 'giturdone_quiz/base.html' %}

{% block title %}Git Ur Done Reset Scores{% endblock %}



{% block body %}

<div class="w3-container w3-yellow">

    <center>
    <h2 style="color:blue">Your Scores Have Been Zeroed!</h2>
    </center>

<p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
</div>
{% endblock %}